### PR TITLE
Chapter 8 

### PR DESCRIPTION
**Pull request by rhmtrz**
- [x]  print "Hello World"

- [ ]  print "my-name"

---
This change is [Reviewable](https://reviewable.io/reviews/tigerscave/rah-scheme-dojo/3)

### CODE REVIEW

**Comment by azamiya** [comment]
> ```
>     
> ```

@rhmtrz why your indent is `space: 4` ?

---

Review status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @rhmtrz)

---

*[chapter-8/calculate.scm, line 3 at r1](https://reviewable.io/reviews/tigerscave/rah-scheme-dojo/3#-LGXawFiBuHRroq4eC5M:-LGXawFiBuHRroq4eC5N:b-44dipy) ([raw file](https://github.com/tigerscave/rah-scheme-dojo/blob/e7ca8100d7b6a5c9be8fc7f8eafbacf295149a82/chapter-8/calculate.scm#L3)):*
> ```Scheme
> 
> 
> (define cualculate2
> ```

:shit: be careful typo

---


*Comments from [Reviewable](https://reviewable.io/reviews/tigerscave/rah-scheme-dojo/3#-:-LGXbAIsBs8KMZzO__y6:b-rr7elw)*

**Comment by rhmtrz** [comment]
- [x] print hello-world
- [x]  simple calculate function with taking a function as an argument
- [x]  calculate-f function take an argument and return a function. 
- [x] rember-f function

**Comment by cdra0624** [comment]
notification test

**Comment by cdra0624** [comment]
test

**Pull request merged**
